import React from 'react'
import Homehero from './components/Homehero/Homehero';
import AnimatedText from './components/AnimatedText/AnimatedText';
import TeacherandStudent from './components/HomeComponents/TeacherandStudent';
import ClientReviewCarousel from '@/app/components/HomeComponents/ClientReviewCarousel';



const page = () => {
  return (
    <>
    <Homehero/>
    <AnimatedText />
    <TeacherandStudent />
    <ClientReviewCarousel />
   
    </>
  )
}

export default page
export const metadata = {
  title: "Home - SSJBC",
  description: "Generated by create next app",
};